# Type stubs for adsk.fusion module
from typing import Any

class Design:
    @staticmethod
    def cast(obj: Any) -> 'Design | None': ...
    @property
    def unitsManager(self) -> 'UnitsManager': ...
    @property
    def fusionUnitsManager(self) -> 'FusionUnitsManager': ...

class UnitsManager:
    @property
    def defaultLengthUnits(self) -> str: ...

class FusionUnitsManager:
    @property
    def distanceDisplayUnits(self) -> 'DistanceUnits': ...

class DistanceUnits:
    InchDistanceUnits: 'DistanceUnits'
    MillimeterDistanceUnits: 'DistanceUnits'
    CentimeterDistanceUnits: 'DistanceUnits'

class SketchEntity:
    @property
    def parentSketch(self) -> 'Sketch | None': ...

class SketchCurve(SketchEntity):
    @property
    def startSketchPoint(self) -> 'SketchPoint': ...
    @property
    def endSketchPoint(self) -> 'SketchPoint': ...
    @property
    def parentSketch(self) -> 'Sketch': ...

class SketchLine(SketchCurve):
    @staticmethod
    def cast(obj: Any) -> 'SketchLine | None': ...
    @property
    def length(self) -> float: ...
    @property
    def startSketchPoint(self) -> 'SketchPoint': ...
    @property
    def endSketchPoint(self) -> 'SketchPoint': ...

class SketchArc(SketchCurve):
    @staticmethod
    def cast(obj: Any) -> 'SketchArc | None': ...
    @property
    def radius(self) -> float: ...
    @property
    def length(self) -> float: ...
    @property
    def centerSketchPoint(self) -> 'SketchPoint': ...
    @property
    def startSketchPoint(self) -> 'SketchPoint': ...
    @property
    def endSketchPoint(self) -> 'SketchPoint': ...
    @property
    def geometry(self) -> 'Arc3D': ...

class SketchPoint:
    @property
    def geometry(self) -> 'Point3D': ...
    @property
    def worldGeometry(self) -> 'Point3D': ...

class Point3D:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def distanceTo(self, point: 'Point3D') -> float: ...
    def isEqualTo(self, point: 'Point3D') -> bool: ...
    @staticmethod
    def create(x: float, y: float, z: float) -> 'Point3D': ...

class Vector3D:
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    @property
    def length(self) -> float: ...
    def normalize(self) -> bool: ...
    def crossProduct(self, vector: 'Vector3D') -> 'Vector3D': ...
    def dotProduct(self, vector: 'Vector3D') -> float: ...
    @staticmethod
    def create(x: float, y: float, z: float) -> 'Vector3D': ...

class Arc3D:
    @property
    def center(self) -> Point3D: ...
    @property
    def normal(self) -> Vector3D: ...

class Attributes:
    def itemByName(self, groupName: str, name: str) -> 'Attribute | None': ...
    def add(self, groupName: str, name: str, value: str) -> 'Attribute': ...

class Attribute:
    @property
    def value(self) -> str: ...
    def deleteMe(self) -> bool: ...

class Sketch:
    @property
    def name(self) -> str: ...
    @property
    def parentComponent(self) -> 'Component': ...
    @property
    def attributes(self) -> Attributes: ...

class Component:
    @property
    def name(self) -> str: ...
    @property
    def attributes(self) -> Attributes: ...

class Occurrence:
    @property
    def name(self) -> str: ...
    @property
    def component(self) -> Component: ...
